// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SongVoting.API.Models.Database;

namespace SongVoting.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SongVoting.API.Models.Database.SpotifyTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Added")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpotifyId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SpotifyTracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(2575),
                            SpotifyId = "3KTikFVuiStwKvcIW0Y0uJ"
                        },
                        new
                        {
                            Id = 2,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3031),
                            SpotifyId = "5vMzNmHm2ec2zrqiYhkQzZ"
                        },
                        new
                        {
                            Id = 3,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3049),
                            SpotifyId = "0rH0mprtecH3grD9HFM5AD"
                        },
                        new
                        {
                            Id = 4,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3050),
                            SpotifyId = "4G29gmjS7Z2nEFeM7FA6wx"
                        },
                        new
                        {
                            Id = 5,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3050),
                            SpotifyId = "1Yqj7oGrttZH3JX2RYTmzS"
                        },
                        new
                        {
                            Id = 6,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3051),
                            SpotifyId = "5Bp8uC0h4CjxENVBnahOkD"
                        },
                        new
                        {
                            Id = 7,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3052),
                            SpotifyId = "2a1aibn4UgSkeTaxJSWw1L"
                        },
                        new
                        {
                            Id = 8,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3052),
                            SpotifyId = "78twEEzRCHmOzgRn7wAl8I"
                        },
                        new
                        {
                            Id = 9,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3053),
                            SpotifyId = "7mj5fT0Biju5jR41m9ghUl"
                        },
                        new
                        {
                            Id = 10,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3053),
                            SpotifyId = "5AcdaSVQfLcUKMaqchfBie"
                        },
                        new
                        {
                            Id = 11,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3054),
                            SpotifyId = "5lubagonZYGdyrfbBsOYdy"
                        },
                        new
                        {
                            Id = 12,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3054),
                            SpotifyId = "5HWBaiVcqnaUf3BI4tfYG5"
                        },
                        new
                        {
                            Id = 13,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3055),
                            SpotifyId = "0pvGqtwpBePPYdEVzdtXWe"
                        },
                        new
                        {
                            Id = 14,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3056),
                            SpotifyId = "3i65fj9NX9PPNTDKyhlWvP"
                        },
                        new
                        {
                            Id = 15,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3056),
                            SpotifyId = "4EiKZxDgW0sbT8BZ9Gl6dC"
                        },
                        new
                        {
                            Id = 16,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3057),
                            SpotifyId = "6Nenm0bjHwjCbTet7Zb9VH"
                        },
                        new
                        {
                            Id = 17,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3057),
                            SpotifyId = "0gI1wucmc2djSV3e25LqCd"
                        },
                        new
                        {
                            Id = 18,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3058),
                            SpotifyId = "5SDcksP8En1l6RtTY1wzHc"
                        },
                        new
                        {
                            Id = 19,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3058),
                            SpotifyId = "0jxIbgW2FoPhqgTh5qhegg"
                        },
                        new
                        {
                            Id = 20,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3059),
                            SpotifyId = "3agx8NSEa7IPUxvbQs5Xax"
                        },
                        new
                        {
                            Id = 21,
                            Added = new DateTime(2020, 1, 2, 17, 26, 45, 869, DateTimeKind.Utc).AddTicks(3060),
                            SpotifyId = "50lW1fKoDtyKaiR2bR7ksl"
                        });
                });

            modelBuilder.Entity("SongVoting.API.Models.Database.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Added")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Liked")
                        .HasColumnType("bit");

                    b.Property<int>("SpotifyTrackId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserToken")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SpotifyTrackId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("SongVoting.API.Models.Database.Vote", b =>
                {
                    b.HasOne("SongVoting.API.Models.Database.SpotifyTrack", null)
                        .WithMany("Votes")
                        .HasForeignKey("SpotifyTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
